services : 
	nginx :
		build : nginx
		#healthcheck:
			#test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
			#interval: 10s
			#timeout: 10s
			#retries: 3  
	
	# Wrapper to run VEP in the background as an internal API service 
	# that the app can then talk to.
	vep-utr-annotator : 
		# Create Image
		build : 
			context : ./vep_utr_annotator
			dockerfile : Dockerfile
		
		stop_signal: SIGINT # The devserver only stops on SIGINT.
		stdin_open: true
		tty: true
		user: vep
		ports:
			- "8000:8000"
		# Create volume mounts to install UTR annotator
		volumes : vep_utr_annotator/UTRannotator-vep-plugin:/opt/vep/.vep/Plugins/UTRannotator-vep-plugin 
		#healthcheck:

		# Run the INSTALL-pl to install cache
		#command : 

	app : 
		depends_on : 
			- nginx
		build :  
			context : .
			dockerfile: Dockerfile
		ports : 
			- "5000:5000"