version: "3.7"
services:
  app:
    build: flask-app
    ports:
      - "8080:8080"
    volumes:
      - "../pipeline/database/features.db:/features.db"
      - "../pipeline/database/test.db:/test.db"
      - "../utr_utils/:/utr_utils"
