services : 
	nginx :
		build : nginx
		restart : always
		ports : 
			- 80:80 
			- 443:443 # To be added once we have ssl encryption
		networks : 
			- appnet
		#healthcheck:
			#test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
			#interval: 10s
			#timeout: 10s
			#retries: 3  
	app : 
		depends_on : 
			- nginx
		build : flask-app
		ports : 
			- "5000:5000"
