name: utr-app-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - astroid=2.7.3
  - blas=1.0=mkl
  - bottleneck=1.3.2
  - ca-certificates=2021.7.5
  - cffi=1.14.6
  - cfgv=3.3.1
  - colorama=0.4.4
  - distlib=0.3.2
  - editdistance-s=1.0.0
  - filelock=3.0.12
  - identify=2.2.13
  - intel-openmp=2021.3.0
  - isort=5.9.3
  - lazy-object-proxy=1.6.0
  - ld_impl_linux-64=2.36.1
  - libffi=3.3
  - mccabe=0.6.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nodeenv=1.6.0
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1k
  - pandas=1.3.2
  - platformdirs=2.3.0
  - pre-commit=2.14.1
  - pycparser=2.20
  - pylint=2.10.2
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - setuptools=57.4.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - tzdata=2021a
  - virtualenv=20.4.7
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
