name: utr-app-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - appdirs=1.4.4
  - astroid=2.7.3
  - bcftools=1.14
  - blas=1.0
  - bokeh=2.4.1
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cffi=1.14.6
  - cfgv=3.3.1
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cytoolz=0.11.2
  - dask=2021.11.1
  - dask-core=2021.11.1
  - distlib=0.3.2
  - distributed=2021.11.1
  - editdistance-s=1.0.0
  - filelock=3.0.12
  - freetype=2.11.0
  - fsspec=2021.11.0
  - greenlet=1.1.2
  - gsl=2.6
  - heapdict=1.0.1
  - htslib=1.14
  - identify=2.2.13
  - intel-openmp=2021.3.0
  - isort=5.9.3
  - jbig=2.1
  - jinja2=3.0.3
  - jpeg=9d
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20210714
  - libev=4.33
  - libffi=3.4.2
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - mccabe=0.6.1
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - msgpack-python=1.0.2
  - ncurses=6.2
  - nodeenv=1.6.0
  - numexpr=2.7.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.0.0
  - packaging=21.2
  - pandas=1.3.2
  - partd=1.2.0
  - perl=5.32.1
  - pillow=8.4.0
  - pip=21.2.4
  - platformdirs=2.3.0
  - pre-commit=2.14.1
  - psutil=5.8.0
  - pycparser=2.20
  - pylint=2.10.2
  - pyparsing=2.4.7
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - setuptools=57.4.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlalchemy=1.4.27
  - sqlite=3.36.0
  - tabix=1.11
  - tbb=2021.3.0
  - tblib=1.7.0
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - virtualenv=20.4.7
  - wheel=0.37.0
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - certifi==2021.5.30
    - charset-normalizer==2.0.6
    - idna==3.2
    - numpy==1.21.2
    - requests==2.26.0
    - sqlitedict==1.7.0
    - urllib3==1.26.7
